# main menu
[[main]]
name = "Services"
url = "#services"
weight = 2

[[main]]
name = "Team"
url = "#team"
weight = 3

[[main]]
name = "Partners"
url = "#partners"
weight = 4

[[main]]
name = "Contact"
url = "#contact"
weight = 5

[[main]]
name = "Blog"
url = "blog/"
weight = 9

# footer menu
#[[footer]]
#name = "About"
#url = "about/"
#weight = 1
#
#[[footer]]
#name = "Blog"
#url = "blog/"
#weight = 2
#
#[[footer]]
#name = "Blog Details"
#url = "blog/post-1/"
#weight = 3
#
#[[footer]]
#name = "Terms & Conditions"
#url = "terms-and-conditions/"
#weight = 4
